version: '3'
services:
  top.api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: api
    container_name: hackTv_api
    ports:
      - "8000:8000"
    volumes:
      - ./env:/opt/app/.env
      - ./uploads:/opt/app/uploads
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: front
    container_name: hackTv_front
    ports:
      - "3000:3000"
    volumes:
          - ./env:/opt/app/.env
